project/mainproject/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path("", views.index, name="index"),
    path("edit/time_frame/", views.edit_time_frame, name="edit_time_frame"),
    path("add_class/<int:id_day_of_week>/<int:id_period>/", views.home_edit, name="home_edit"),
    path("delete/<int:class_id>/<int:id_day_of_week>/<int:id_period>/", views.delete_class, name="delete_class"),
    path("class_edit/<int:class_id>/", views.class_edit, name="class_edit"),
    path("update/class_basic_info/", views.update_class_basic_info, name="update_class_basic_info"),
    path("update/memo/", views.update_memo, name="update_memo"),
    path("update/homework/", views.update_homework, name="update_homework"),
    path("update/homework/finish/", views.finish_homework, name="finish_homework"),
    path("delete/memo/", views.delete_memo, name="delete_memo"),
    path("delete/homework/", views.delete_homework, name="delete_homework"),
]

project/mainproject/display_homework/urls.py
from django.urls import path
from .views import display_homework
 
urlpatterns = [
    path("display_homework", display_homework, name="display_homework"),
]

project/mainproject/mainproject/urls.py
from django.contrib import admin
from django.urls import path,include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("app.urls", "app"), namespace="app")),
    path("accounts/", include("accounts.urls")),
    path("", include(("display_homework.urls", "display_homework"), namespace="display_homework")),
]

project/mainproject/app/templates/app/includes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head prefix="og: https://ogp.me/ns#">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <meta property="og:url" content="{{ request.build_absolute_uri }}" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="{% block og_title %}{% endblock %} | Sync Schedule"/>
        <meta property="og:description" content="Sync Scheduleは、同一の授業を複数のコマに配置可能な時間割管理アプリです。" />
        <meta property="og:site_name" content="Sync Schedule" />
        <meta property="og:locale" content="ja_JP" /> 
        <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'img/og_screenshot.jpg' %}" />
        <meta name="twitter:card" content="summary_large_image" />

        <link rel="icon" type="image/png" href="{% static 'favicons/favicon-96x96.png' %}" sizes="96x96"/>
        <link rel="icon" type="image/svg+xml" href="{% static 'favicons/favicon.svg' %}"/>
        <link rel="shortcut icon" href="{% static 'favicons/favicon.ico' %}"/>
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}"/>
        <meta name="apple-mobile-web-app-title" content="Sync Schedule" />
        <link rel="manifest" href="{% static 'favicons/site.webmanifest' %}"/>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" xintegrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'css/global-menu.css' %}">
        <link rel="stylesheet" href="{% static 'css/footer.css' %}">
        {% block extra_css %}
            
        {% endblock extra_css %}
        <meta name="description" content="SyncScheduleは、同一の授業を複数のコマに配置可能な時間割管理アプリです。">
        <title>{% block title %}{% endblock title %} | SyncSchedule</title>
    </head>
    <body>
        {% include "app/includes/global-menu.html" %}
        
        {% block content %}
            
        {% endblock content %}

        {% include "app/includes/footer.html" %}
            
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" xintegrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="{% static 'js/global-menu.js' %}"></script>
        {% block extra_js %}
            
        {% endblock extra_js %}
            
    </body>
</html>

project/mainproject/app/templates/app/includes/footer.html
<footer>
    <nav class="navbar">
        {% if user.is_authenticated %}
        <div class="nav-item">
            <a class="nav-link menu-link" href="{% url 'display_homework:display_homework' %}">
                <i class="bi bi-list-task"></i> 課題一覧
            </a>
        </div>
        <div class="nav-item">
            <a class="nav-link menu-link" href="{% url 'app:index' %}">
                <i class="bi bi-journal-text"></i> 授業一覧
            </a>
        </div>
        {% else %}
        <div class="nav-item nav-auth"><a class="nav-link btn-auth" href="{% url 'login' %}">ログイン</a></div>
        <div class="nav-item nav-auth"><a class="nav-link btn-auth" href="{% url 'signup' %}">新規登録</a></div>
        {% endif %}
    </nav>
</footer>

project/mainproject/app/templates/app/includes/global-menu.html
<header>
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="{% url 'app:index' %}">
            <i class="bi bi-calendar-check" ></i> SyncSchedule
        </a>
        
        <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon navbar-dark"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if user.is_authenticated %}
            <ul class="navbar-nav me-auto navbar-menu-link">
                <li class="nav-item">
                    <a class="nav-link menu-link" href="{% url 'display_homework:display_homework' %}">
                        <i class="bi bi-list-task"></i> 課題一覧
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link menu-link" href="{% url 'app:index' %}">
                        <i class="bi bi-journal-text"></i> 授業一覧
                    </a>
                </li>
            </ul>
            {% endif %}
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="nav-link disable">こんにちは, <span style="color: white; font-weight: bold;">{{ user.username }}</span> さん</span>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'logout' %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link nav-link btn-logout">ログアウト</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item nav-auth"><a class="nav-link btn-auth" href="{% url 'login' %}">ログイン</a></li>
                    <li class="nav-item nav-auth"><a class="nav-link btn-auth" href="{% url 'signup' %}">新規登録</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>