project/mainproject/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path("", views.index, name="index"),
    path("edit/time_frame/", views.edit_time_frame, name="edit_time_frame"),
    path("add_class/<int:id_day_of_week>/<int:id_period>/", views.home_edit, name="home_edit"),
    path("delete/<int:class_id>/<int:id_day_of_week>/<int:id_period>/", views.delete_class, name="delete_class"),
    path("class_edit/<int:class_id>/", views.class_edit, name="class_edit"),
    path("update/class_basic_info/", views.update_class_basic_info, name="update_class_basic_info"),
    path("update/memo/", views.update_memo, name="update_memo"),
    path("update/homework/", views.update_homework, name="update_homework"),
    path("update/homework/finish/", views.finish_homework, name="finish_homework"),
    path("delete/memo/", views.delete_memo, name="delete_memo"),
    path("delete/homework/", views.delete_homework, name="delete_homework"),
]

project/mainproject/mainproject/urls.py
from django.contrib import admin
from django.urls import path,include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("app.urls", "app"), namespace="app")),
    path("accounts/", include("accounts.urls")),
    path("", include(("display_homework.urls", "display_homework"), namespace="display_homework")),
]

project/mainproject/app/templates/app/class-edit.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" xintegrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/class-edit.css' %}">
    <link rel="stylesheet" href="{% static 'css/global-menu.css' %}">
    <title>授業編集 | SyncSchedule</title>

</head>
<body>
    {% include "app/includes/global-menu.html" %}
    <main class="container">
        <a class="btn btn-outline-secondary mb-3" href="{% url 'app:index' %}">
            <i class="bi bi-arrow-left"></i>戻る
        </a>
        
        <div class="card class-item mb-5">
            <div class="card-header d-flex bg-transparent border-bottom-0 pt-4 px-4">
                <h2 class="item-title" id="class-basic-info-{{subject.pk}}-class-name" style="padding-left: 5px; font-size: 1.5rem; border-left: 6px solid {{ subject.color }};">
                    {{ subject.class_name }}
                </h2>
                <button type="button" class="btn btn-outline-secondary ms-3 btn-sm border-0" id="edit-class-basic-info-{{subject.pk}}" onclick="toggleEditClass('class-basic-info', '{{ subject.pk }}')">
                    <i class="bi bi-pencil js-display-class-basic-info-{{subject.pk}}"></i>
                    <i class="bi bi-arrow-counterclockwise js-display-class-basic-info-{{subject.pk}} hide-content"></i>
                </button>
            </div>
            <div class="card-body px-4 pb-4">
                <div class="mt-2 js-display-class-basic-info-{{subject.pk}}" id="class-basic-info">
                    
                    <p class="d-flex align-items-center mb-2">
                        <i class="bi bi-geo-alt-fill me-2 text-secondary"></i>
                        {% if subject.classroom_name is not None %}
                        <span id="class-basic-info-{{subject.pk}}-classroom-name">{{ subject.classroom_name }}</span>
                        {% endif %}
                    </p>   

                    
                    <p class="d-flex align-items-center mb-0">
                        <i class="bi bi-person-fill me-2 text-secondary"></i>
                        {% if subject.professor_name is not None %}
                        <span id="class-basic-info-{{subject.pk}}-professor-name">{{ subject.professor_name }}</span>
                        {% endif %}
                    </p>
                        
                </div>
                
                <form class="mb-0 js-display-class-basic-info-{{subject.pk}} hide-content" method="post" id="edit-form-class-basic-info-{{subject.pk}}" onsubmit="updateClassBasicInfo(event, '{{ subject.pk }}')">
                    {% csrf_token %}
                        <p>
                            {{ class_basic_info_form.class_name.label_tag }}
                            {{ class_basic_info_form.class_name }}

                            {{ class_basic_info_form.classroom_name.label_tag }}
                            {{ class_basic_info_form.classroom_name }}

                            {{ class_basic_info_form.professor_name.label_tag }}
                            {{ class_basic_info_form.professor_name }}

                            {{ class_basic_info_form.color.label_tag }}

                            <div class="color-radio-grid">
                                {% for color_radio in class_basic_info_form.color %}
                                <div class="color-option">
                                    {{ color_radio.tag }} <label for="{{ color_radio.id_for_label }}" style="background-color: {{ color_radio.data.value }};">
                                        {{ color_radio.choice_label }}
                                    </label>
                                </div>
                                {% endfor %}
                            </div>
                        </p>
                    <button class="btn btn-primary mt-3" type="submit">変更</button>
                </form>
            </div>
        </div>
    
        <div class="mb-5">
            <div class="align-items-center d-flex border-bottom pb-2 mb-3">
                <h3 class="item-title m-0">宿題</h3>
                <button type="button" id="btn-add-homework" class="btn btn-link btn-lg text-decoration-none ms-auto p-0" style="line-height: 1;">
                    <i class="bi bi-plus-circle-fill add-item-button"></i>
                </button>
            </div>
            
            <div id="homework-form" class="class-edit-form">
                <div class="class-edit-form-content class-item">
                    <form class="mb-0" method="post">
                        {% csrf_token %}
                        {{ homework_form.as_p }}
                        <div class="text-end">
                            <button class="btn btn-primary mt-2" type="submit" name="submit-homework-form">追加</button>
                        </div>
                    </form>
                </div>
            </div>

            {% for homework in homeworks %}
                <div class="card class-item {% if homework.item.is_finished %} finished {% endif %}" id="homework-{{homework.item.pk}}">
                    <div class="card-body d-flex flex-column">
                        <div class="d-flex justify-content-end mb-2">
                            <button type="button" class="btn btn-sm btn-outline-secondary me-2 btn-edit-homework border-0" id="edit-homework-{{homework.item.pk}}" onclick="toggleEditClass('homework', '{{ homework.item.pk }}')">
                                <i class="bi bi-pencil js-display-homework-{{homework.item.pk}}"></i>
                                <i class="bi bi-arrow-counterclockwise js-display-homework-{{homework.item.pk}} hide-content"></i>
                            </button>
                            <button type="button" class="btn btn-sm btn-outline-danger btn-delete-homework border-0" id="delete-homework-{{homework.item.pk}}" onclick="deleteHomework('{{homework.item.pk}}')">
                                <i class="bi bi-trash"></i>
                            </button>
                        </div>
    
                        <div class="d-flex align-items-start js-display-homework-{{homework.item.pk}}">
                            <div class="form-check me-3">
                                <input type="checkbox" class="form-check-input" id="homework-{{ homework.item.pk }}-checkbox" value="" {% if homework.item.is_finished %} checked {% endif %} onclick="finish_homework('{{homework.item.pk}}')">
                            </div>
                            <label class="card-text flex-grow-1 {% if homework.item.is_finished %}homework-finished{% endif %}" for="homework-{{ homework.item.pk }}-checkbox" style="cursor: pointer;">
                                <div class="text-muted small mb-1">
                                    締め切り: <span id="homework-{{ homework.item.pk }}-deadline" class="fw-bold">{{ homework.item.deadline|date:"Y年m月d日" }}</span>
                                </div>
                                <div id="homework-{{ homework.item.pk }}-content" class="fs-6">
                                    {{ homework.item.content|linebreaksbr }}
                                </div>
                            </label>
                        </div>

                        <form class="mt-3 form-edit-homework js-display-homework-{{homework.item.pk}} hide-content" method="post" id="edit-form-homework-{{homework.item.pk}}" onsubmit="updateHomework(event, '{{ homework.item.pk }}')">
                            {% csrf_token %}
                            {{ homework.form.as_p }}
                            <div class="text-end">
                                <button class="btn btn-primary mt-2" type="submit">変更</button>
                            </div>
                        </form>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="mb-5">
            <div class="align-items-center d-flex border-bottom pb-2 mb-3">
                <h3 class="item-title m-0">メモ</h3>
                <button type="button" id="btn-add-memo" class="btn btn-link btn-lg text-decoration-none ms-auto p-0" style="line-height: 1;">
                    <i class="bi bi-plus-circle-fill add-item-button"></i>
                </button>
            </div>

            <div id="memo-form" class="class-edit-form">
                <div class="class-edit-form-content class-item">
                    <form class="mb-0" method="post">
                        {% csrf_token %}
                        {{ memo_form.as_p }}
                        <div class="text-end">
                            <button class="btn btn-primary mt-2" type="submit" name="submit-memo-form">追加</button>
                        </div>
                    </form>
                </div>
            </div>

            {% for memo in memos %}
            <div class="card class-item" id="memo-{{memo.item.pk}}">
                <div class="card-body">
                    <div class="d-flex justify-content-end mb-2">
                        <button type="button" class="btn btn-sm btn-outline-secondary me-2 btn-edit-memo border-0" id="edit-memo-{{memo.item.pk}}" onclick="toggleEditClass('memo', '{{ memo.item.pk }}')">
                            <i class="bi bi-pencil js-display-memo-{{memo.item.pk}}"></i>
                            <i class="bi bi-arrow-counterclockwise hide-content js-display-memo-{{memo.item.pk}}"></i>
                        </button>
                        <button type="button" class="btn btn-sm btn-outline-danger btn-delete-memo border-0" id="delete-memo-{{memo.item.pk}}" onclick="deleteMemo('{{memo.item.pk}}')">
                            <i class="bi bi-trash"></i>
                        </button>
                    </div>

                    <div class="card-text js-display-memo-{{memo.item.pk}} px-2" id="memo-{{memo.item.pk}}-content">
                        {{ memo.item.content|linebreaksbr }}
                    </div>
                    
                    <form class="mt-3 js-display-memo-{{memo.item.pk}} form-edit-memo hide-content" method="post" id="edit-form-memo-{{memo.item.pk}}" onsubmit="updateMemo(event, '{{ memo.item.pk }}')">
                        {% csrf_token %}
                        {{ memo.form.as_p }}
                        <div class="text-end">
                            <button class="btn btn-primary mt-2" type="submit">変更</button>
                        </div>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" xintegrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/class-edit.js' %}"></script>

</body>
</html>

project/mainproject/app/templates/app/home-edit.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" xintegrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/home-edit.css' %}">    
    <link rel="stylesheet" href="{% static 'css/global-menu.css' %}">
    <title>授業設定 | SyncSchedule</title>

</head>
<body>
    {% include "app/includes/global-menu.html" %}

    <main class="container">
        
        <a class="btn btn-outline-secondary mb-3" href="{% url 'app:index' %}?edit_mode=on">
            <i class="bi bi-arrow-left"></i>戻る
        </a>
        <div class="nav nav-tabs">
            <button class="nav-link class-form active" type="button">
                新しい授業を追加
            </button>
            <button class="nav-link schedule-form" type="button">
                既存の授業から追加
            </button>
        </div>

        <div class="edit-card">
            <div class="tab-content">
                
                <div class="tab-item class-form active">
                    <form method="post">
                        {% csrf_token %}
                        <p>
                            
                            {{ class_form.class_name.label_tag }}
                            {{ class_form.class_name }}

                            {{ class_form.classroom_name.label_tag }}
                            {{ class_form.classroom_name }}

                            {{ class_form.professor_name.label_tag }}
                            {{ class_form.professor_name }}

                            {{ class_form.color.label_tag }}

                            <div class="color-radio-grid">
                                {% for color_radio in class_form.color %}
                                <div class="color-option">
                                    {{ color_radio.tag }} <label for="{{ color_radio.id_for_label }}" style="background-color: {{ color_radio.data.value }};">
                                        {{ color_radio.choice_label }}
                                    </label>
                                </div>
                                {% endfor %}
                            </div>
                        </p>
                        <div style="display: none;">
                            {{ schedule_form }}
                        </div>
                        <button class="btn btn-submit mt-3" type="submit">決定</button>
                    </form>
                </div>

                <div class="tab-item schedule-form fading-out">
                    <form method="post">
                        {% csrf_token %}
                        <div style="display: none;">
                            {{ class_form }}
                        </div>
                        {{ schedule_form.as_p }}
                        <button class="btn btn-submit mt-3" type="submit">決定</button>
                    </form>
                </div>
                
            </div>
        </div>
    
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" xintegrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/homeEdit.js' %}"></script>
</body>
</html>

project/mainproject/app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" xintegrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/global-menu.css' %}">
    <title>SyncSchedule</title>

</head>

<body {% if is_editing %} data-is-editing="true" {% endif %} data-timetable-row="{{ timetable_row }}" data-timetable-column="{{ timetable_column }}">
    
    {% include "app/includes/global-menu.html" %}

    <main class="timetable-grid">
        <div class="col">
            <div class="card" style="background: transparent; box-shadow: none;">
                <button type="button" class="btn btn-secondary" id="home-edit-button">編集</button>
            </div>
        </div>

        
        {% for context in period_context %}
            
        {% if context.exist %}
        <div class="col">
            <div class="card info-card time-frame">
                <div class="card-body">
                    第{{ forloop.counter }}限<br>
                    <span class="time-frame-text" id="time-frame-text-{{ forloop.counter }}">{{ context.time_frame.start_time }} - {{ context.time_frame.end_time }}</span>
                </div>
                
                <form class="time-frame-form home-edit-display" id="time-frame-form-{{ forloop.counter }}" method="post" data-id="{{ forloop.counter }}">
                    {% csrf_token %}
                    {{ context.form.period }}
                    {{ context.form.start_time }}
                    {{ context.form.end_time }}
                </form>
            </div>
        </div>
        {% else %}
        <div class="home-edit-display">
            <div class="col">
                <div class="card info-card time-frame">
                    <div class="card-body">
                        第{{ forloop.counter }}限<br>
                        <span class="time-frame-text">{{ context.time_frame.start_time }} - {{ context.time_frame.end_time }}</span>
                    </div>
                    <form class="time-frame-form home-edit-display" id="time-frame-form-{{ forloop.counter }}" method="post" data-id="{{ forloop.counter }}">
                        {% csrf_token %}
                        {{ context.form.period }}
                        {{ context.form.start_time }}
                        {{ context.form.end_time }}
                        </form>
                </div>  
            </div>
        </div>
        {% endif %}
            
        {% endfor %}

        {% for subjects in class_list %}
        
        {% if exist_saturday_class == False and forloop.counter == 6 %}
        <div class="home-edit-display">
            <div class="col">
                <div class="card info-card day-of-week">
                    <div class="card-body">土</div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="col">
            <div class="card info-card">
                <div class="card-body">{% cycle "月" "火" "水" "木" "金" "土" %}</div>
            </div>
        </div>
        {% endif %}
            
        {% for subject in subjects %}
        
        {% if subject.exist_class_par_week and subject.content is not None %}
        <div class="col">
            <a class="class-content card" href="{% url 'app:class_edit' subject.content.id %}" style="background-color: {{ subject.content.color }};">
                <p>{{ subject.content.class_name }}</p>
                
                {% if subject.content.classroom_name is not None %}
                <p>{{ subject.content.classroom_name }}</p>
                {% endif %}
                    
                <div class="home-edit-display">
                    <form method="post" action="{% url 'app:delete_class' subject.content.id forloop.parentloop.counter0  forloop.counter %}" onsubmit="return confirm('この操作は取り消せません。削除しますか？')">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger delete-btn">削除</button>
                    </form>
                </div>
            </a>
        </div>
        {% elif subject.exist_class_par_week %}
        <div class="col">
            <div class="card disabled-card">
                <div class="home-edit-display">
                    <form action="{% url 'app:home_edit' forloop.parentloop.counter forloop.counter %}" method="get">
                        <button type="submit" class="btn btn-outline-secondary home-edit-display">+</button>
                    </form>
                </div>
            </div>
        </div>
        {% else %}
        <div class="home-edit-display">
            <div class="col">
                <div class="card disabled-card">
                    <form action="{% url 'app:home_edit' forloop.parentloop.counter forloop.counter%}" method="get">
                        <button type="submit" class="btn btn-outline-secondary home-edit-display">+</button>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
        
        {% endfor %}
    {% endfor %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" xintegrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>